### ISSUE TITLE
`AcceptSuggestion` doesn't take effect

### ISSUE THREAD

**Issue by hankcs** [telepathylabsai/OpenDF#1] opened 2022-06-02 19:12 UTC
Dear authors,

I've been reading your great paper and experimenting with OpenDF for quite a while. Seems that `AcceptSuggestion` is not correctly implemented as it doesn't really complies to a  confirmation that writes the database. For example, consider the following dialog:

- what is my appointment with janice kang
- _I didn't find any events with janice kang._
- create appointment with janice kang
- _Here are some times when you and Janice Kang are free._
- **yes** `sexp=AcceptSuggestion()`
- **_I've put that on your calendar on Wednesday from 10:00 to 10:30 AM._** 

As highlighted above, the turn in bold doesn't take effect but instead it raises `EventConfirmationException('Does this look ok? ...)` to ask for confirmation again which eventually terminates OpenDF execution.

After digging a little deeper, I find the `confirm` flag is never set to true anywhere. Maybe this is the core problem? Maybe the solution is to set it to true in `AcceptSuggestion` node?

Thanks.

**Comment by guimaraes-tl** [comment] 2022-06-03 10:26
Dear hankcs,

Thank you for your interesting in OpenDF.

In fact, there was a bug during the handling of exceptions, which should be already fixed on the last commit. However, this bug is not related to the `confirm` flag.

By default, when asking OpenDF to create an event, it will suggest you possible time options, if you choose to accept one of these options (using `sexp = AcceptSuggestion()`), it will apply the suggestion to the graph, which will then trigger an exception asking for confirmation, with the suggestion to set the `confirm` flag to `True`. On your example, by design, you will need to confirm the event twice: (1) to accept the time suggestion; and (2) to confirm the event at the given time. Only then the event will be committed to the database.

On the file defs.py you can see a list of options that change how the graph is drawn, by passing `-env show_sugg=True` on the command line argument, you can see the corresponding sexp for each suggestion OpenDF makes. By passing `AcceptSuggestion()`, you are telling OpenDF to take the suggestion of index `1`, from the list, and to run it. Be aware that the list starts at index `0`, and `AcceptSuggestion()` will pick the item with index `1`.

In addition, the database (which is stored on `.../OpenDF/tmp/test.db`, by default) is erased at the beginning and ending of each run, so we can perform experiment without worrying about the state of the database. To help you to debug the result of the creation of the event, you can put a break point just before the database erasing function be called, on `main.py:203`, and take a look to see the events in the database file.

I hope you will be able to run this example now.

Best regards.

**Comment by hankcs** [comment] 2022-06-03 22:27
Thank you so much for your prompt response. I'll experiment later with your suggestions.

**Closed** 2022-07-20 08:52 UTC
